### ISSUE TITLE
:sparkles: Request to add tip or trick to documentation :crystal_ball: 

### ISSUE THREAD

**Issue by arpanaditya** [github/hackathons#20]
In the resource file, both discord and slack are mentioned there. And in my opinion, and according to my previous experiences discord is better for organizing a hacker community as well as for hackathons too. So if you're also thinking the same then you can remove slack from the resource file. This is just a suggestion that came to my mind. 
@mishmanners

**Comment by mishmanners** [comment]
Both are used by the community, so we'll keep both in there.
