### ISSUE TITLE
Image link in readMe needs to be fixed

### ISSUE THREAD

**Issue by PrakashGatiyala** [github/hackathons#39]
![image](https://user-images.githubusercontent.com/34413515/198969897-e432e9c7-cda3-4887-8381-78252515844c.png)

When user click on highlighted image, It is redirected to image itself. 

Ideally, It should redirect to the Home page of this repo.( https://github.com/github/hackathons).

I want to fix this by adding anchor tag. 

Hi @mishmanners  I want to work on this issue. Can you assign it to me?

**Comment by PrakashGatiyala** [comment]
Hi @mishmanners  I have created PR for this. PR link: https://github.com/github/hackathons/pull/40
Please review it and merge it.

**Comment by PrakashGatiyala** [comment]
Hi @mishmanners  Could you please review my PR and merge it

**Comment by mishmanners** [comment]
Maybe don't ping Maintainers multiple times. You pinged on here twice in 4 hours. People do need to sleep....

**Comment by PrakashGatiyala** [comment]
> Maybe don't ping Maintainers multiple times. You pinged on here twice in 4 hours. People do need to sleep....

Thank you very much @MishManners
Sorry for inconvenience for tagging you multiple time
